import logging
import time

from queue import Queue, Empty
from trackmania_gym.game_interaction.ipc_fields import IPCCommands, IPCFields
from trackmania_gym.game_interaction.tminterface_commands import TMInterfaceCommands

class TMICommunicationFaildException(Exception):
    """Custom exception for the error repeatedely encountered during training."""
    def __init__(self, n_tries: str, message: str = None):
        if message is None:
            message = f"Process Wrapper did not handle command correctly. Tried {n_tries} times."
        super().__init__(message)

class WrongCMDIDException(Exception):
    def __init__(self, valid_ids : list[int], actual_id : int, message : str = None):
        if message is None:
            message = f"Id in response {actual_id} was not within valid ids {valid_ids}"
        super().__init__(message)

class ResponseIsErrorException(Exception):
    def __init__(self, message : str = ""):
        super().__init__(f"Response was STATUS_ERROR with Message : {message}.")

class IPCommandSender:
    """This class is a helper class that implements error-handling logic when communicating with the TMIProcessWrapper"""

    def __init__(self,
            command_queue : Queue,
            response_queue : Queue,
            timeout : float = 15,
            mcs : int = 2,
            wfr : float = 0.5):
        """
        Docstring for __init__
        
        Args:
            command_queue (Queue)   : Multiprocess-Queue linked to process-wrapper
            response_queue (Queue)  : Multiprocess-Queue linked to process-wrapper
            timeout (float)         : Amount of time in seconds until timeout error is thrown. Default is 15 seconds.
            mcs (int)               : Maximum-Command-Sends ; Maximum amount of tries a command is re-sent until failure is deduced.
            wfr (float)             : Wait-time (in seconds) between retrying
        """


        self.command_queue = command_queue
        self.response_queue = response_queue

        self.logger = logging.getLogger(self.__class__.__name__)
        self.mcs = mcs
        self.ipc_cmd_id = 0
        self.timeout = timeout
        self.waitingperiod_for_retry : float = wfr

        self.useable = True
        """If this class detects an error from its linked process-wrapper then it sets this variable to false; from this moment out all communication with the 
        process wrapper cannot be done anymore, as the syncloop has failed and the process wrapper cannot return any responses."""

        self.retry_ids = []



    def get_command_id(self) -> int:
        """Returns an unused ipc-command-id."""
        self.ipc_cmd_id += 1
        return self.ipc_cmd_id

    def send_command(self, command : dict[str, any]) -> dict[str, any]:
        """Sends a command to the process-wrapper
        Args:
            command (dict)  : Command to send to the ProcessWrapper. This should be generated by IPCCommands.
        Returns:
            response (dict) : Response from the Process-Wrapper. If no response could be aquired, throws TMICommunicationFaildException """
        if not self.useable:
            raise TMICommunicationFaildException("No further communication with process-wrapper possible.")
        command[IPCFields.CMD_ID] = self.get_command_id()

        attempt = 0
        possible_cmd_ids = []
        retry = True
        while attempt <= self.mcs:

            try:

                if retry:
                    self.command_queue.put_nowait(command)
                    possible_cmd_ids.append(command[IPCFields.CMD_ID])

                response = self.response_queue.get(timeout=self.timeout)
                
                RCID = response[IPCFields.CMD_ID] # RID = Response Command ID

                if RCID == -1: # exception in syncloop execution, no recovery possible.
                    self.useable = False
                    self.logger.error(response[IPCFields.ERROR])
                    raise TMICommunicationFaildException("Got exception in syncloop execution from wrapper. See logs.")

                # check if the RCID was valid and expected (if yes, remove it from the possible cmd-ids), if not, continue the loop without retrying
                if self._handle_RCID(RCID, possible_cmd_ids):
                    retry = False
                    continue
                else:
                    possible_cmd_ids.remove(RCID)

                # check response is not an error 
                if not response[IPCFields.STATUS] == IPCFields.STATUS_OK:
                    self.logger.error(f"Got error when executing command {command[IPCFields.CMD]}, with message : {response[IPCFields.ERROR]}")
                    raise ResponseIsErrorException(response[IPCFields.ERROR])
                
                # before returning response, add all possible, unchecked cmd-ids to global checks
                for cmid in possible_cmd_ids:
                    self.retry_ids.append(cmid)

                return response
            except Empty as e:
                self.logger.error(f"Tried sending commmand '{command[IPCFields.CMD_ID]}' {attempt} times and got no response; queue is empty.")
            except TimeoutError as tr:
                self.logger.error(f"Tried sending commmand '{command[IPCFields.CMD_ID]}' {attempt} times and got timeout error.")
            except ResponseIsErrorException as rie:
                self.logger.error(f"Tried sending commmand '{response[IPCFields.CMD_ID]}' {attempt} times and got ResponseIsErrorException")

            command, attempt, retry = self._prepare_retry(command, attempt)

        raise TMICommunicationFaildException(n_tries=attempt, message="Were not able to send command even after multiple tries.") # <- If this happens; the responding end most likely crashed.
    

    def _handle_RCID(self, rcid : int, possible_cmd_ids : list[int]) -> bool:
        if rcid in possible_cmd_ids: # everything is fine with response id
            return False 


        elif rcid in self.retry_ids:
            self.logger.warning(f"Got a global retry-ID from the process wrapper : {rcid}. Removing.")
            self.retry_ids.remove(rcid)
            return True

        else: # something went terribly wrong
            self.logger.error(f"Response-ID : {rcid} was neither in possible_cmd_ids : {possible_cmd_ids}, nor in global-retry-ids : {self.retry_ids}")
            return True 
        

    def _prepare_retry(self, command : dict[str, any], attempt : int) -> tuple[dict[str, any], int, bool]:
        time.sleep(self.waitingperiod_for_retry)

        self.ipc_cmd_id += 1
        command[IPCFields.CMD_ID] = self.ipc_cmd_id # overwrite command id with increased id, otherwise process wrapper will flag it as a seen ID and return error automatically
        return command, attempt + 1, True
    

    def set_gamespeed(self, game_speed : int):
        """Utility method to set game-speed via the process-wrapper"""
        self.send_command(IPCCommands.get_cmd_command(TMInterfaceCommands.set_variable(TMInterfaceCommands.Variables.SPEED, value=game_speed)))

    def set_countdownspeed(self, countdown_speed : int):
        """Utility method to set countdown-speed via the process-wrapper"""
        self.send_command(IPCCommands.get_cmd_command(TMInterfaceCommands.set_variable(TMInterfaceCommands.Variables.COUNTDOWN_SPEED, value=countdown_speed)))