env:
  _partial_: True
  _target_: trackmania_env.envs.single_agent_env2.TMNF_Single_Agent_Env
  position_buffer_size : 20
  position_moved_threshold : 0.8
  reset_mode : "respawn"
  reward_calculator : "nextpoint"
  obs_manager : "nextpointobs" ##use basic for other
  termination_manager : "no_progress"
  game_speed : 70
  countdown_speed : 70
  test : False
  wrap_obs_in_test : false  # Applies an test-wrapper to the observations.
  n_previous_actions : 10
  camera_id : 2
  # these ones are important for termination manager
  max_steps_until_reset : 2049  ##aka timeout
  ignore_stuck_for_n_steps_after_reset : 80 
  increase_timeout_intervals : ## total environment steps after which an increase of timeout happens
    - 124000
    - 1000000
  new_timeouts : ## specifies new values for increase of timeout (initial value is max_steps_until_reset)
    - 512
    - 1024
  terminate_after_steps_without_progress : 1024

  automatic_prevent_sim_finish : true #This basically has to be true; If this is set to false, the environment has to prevent simulation finish itself; which would have to be re-implemented.
  disable_waitforstep_after_n_consecutive_timeouts : 5
  actions_per_second : 20
  waitforstep_timeout_in_s : 1.2 # this HAS to be smaller than the timeout of TMInterface
  use_rewind : true

reward_manager:
  rewardterm_weights:
    accum_distance_weight : 1200
    race_not_finished_weight : 0.05
    race_finished_reward : 100
    other_termination_punishment : 20
    velocity_reward_weight : 1
    backward_weight : 0
    distance_to_center_weight : 1
    velocity_change_reward_weight : 30
    speed_reward_weight: 1
  lateral_distance_mode : "gauss" #triangle, gauss, trapez
    
obsmanager:
  observation_list: 
        - image
        - position
        - velocity
        - yaw_pitch_roll
        - scene_mobil.sync_vehicle_state.speed_forward
        - scene_mobil.input_steer
        - scene_mobil.async_vehicle_state.is_turbo
        - scene_mobil.engine.gear
        - input_finish_event.input_data_field
        - input_accelerate_event.time_field
        - scene_mobil.async_vehicle_state.rest_field
        - rotation_matrix
        
  colorspace : "grayscale"
  convert_torch : true

linesightobsmanager:
  colorspace : "grayscale"
  n_zone_centers_in_inputs : 40
  one_every_n_zone_centers_in_inputs : 20
  n_zone_centers_extrapolate_after_end_of_map : 1000
  n_zone_centers_extrapolate_before_start_of_map : 20
  n_prev_actions_in_inputs : 5
  margin_to_announce_finish_meters : 700
  distance_between_checkpoints: 0.5
  road_width: 90  ## a little bit of margin, could be closer to 24 probably ? Don't take risks there are curvy roads
  sync_virtual_and_real_checkpoints : True



wrappers:
  monitor: 
    _partial_: True
    _target_: stable_baselines3.common.monitor.Monitor 