env:
  _partial_: True
  _target_: trackmania_env.envs.single_agent_env2.TMNF_Single_Agent_Env
  position_buffer_size : 20
  position_moved_threshold : 0.8
  reset_mode : "respawn"
  reward_calculator : "nextpoint"
  obs_manager : "linesight" ##use basic for other
  max_steps_until_reset : 256
  game_speed : 30
  countdown_speed : 50
  test : False
  n_previous_actions : 10
  ignore_stuck_for_n_steps_after_reset : 80 
  increase_timeout_intervals : ## total environment steps after which an increase of timeout happens
    - 500000
    - 1500000
  new_timeouts : ## specifies new values for increase of timeout (initial value is max_steps_until_reset)
    - 512
    - 1024

reward_manager:
  rewardterm_weights:
    accum_distance_wegiht : 1750
    race_not_finished_weight : 0.05
    race_finished_reward : 100
    other_termination_punishment : 0.01
    velocity_reward_weight : 1
    backward_weight : 0
    distance_to_center_weight : 0.25
    velocity_change_reward_weight : 10

obsmanager:
  observation_list: 
        - image
        - position
        - velocity
        - yaw_pitch_roll
        - scene_mobil.sync_vehicle_state.speed_forward
        - scene_mobil.input_steer
        - scene_mobil.async_vehicle_state.is_turbo
        - scene_mobil.engine.gear
        - input_finish_event.input_data_field
        - input_accelerate_event.time_field
        - scene_mobil.async_vehicle_state.rest_field
        - rotation_matrix
        
  colorspace : "rgb"
  convert_torch : true

linesightobsmanager:
  colorspace : "grayscale"
  n_zone_centers_in_inputs : 40
  one_every_n_zone_centers_in_inputs : 20
  n_zone_centers_extrapolate_after_end_of_map : 1000
  n_zone_centers_extrapolate_before_start_of_map : 20
  n_prev_actions_in_inputs : 5
  margin_to_announce_finish_meters : 700
  distance_between_checkpoints: 0.5
  road_width: 90  ## a little bit of margin, could be closer to 24 probably ? Don't take risks there are curvy roads
  sync_virtual_and_real_checkpoints : True



wrappers:
  monitor: 
    _partial_: True
    _target_: stable_baselines3.common.monitor.Monitor 