defaults:
  - platforms: windows.yaml

rl_env:

  obs_manager:
    name: "nextpointobs"
    # image related
    img_width: 128
    img_height: 128
    colorspace: "grayscale"
    camera_id: 2
    # other 
    convert_torch: True
  
  reward_manager:
    name: "nextpoint"
    args:
      accum_distance_weight : 1200
      race_not_finished_weight : 0.05
      race_finished_reward_weight : 100
      other_termination_punishment : 20
      velocity_reward_weight : 1
      backward_weight : 0
      distance_to_center_weight : 1
      velocity_change_reward_weight : 30
      speed_reward_weight: 1
      lateral_distance_mode : "gauss" #triangle, gauss, trapez

  termination_manager:
    name: "no_progress"
    max_steps_until_reset : 2049  ##aka timeout
    ignore_stuck_for_n_steps_after_reset : 80 
    terminate_after_steps_without_progress : 1024    

  env:
    _partial_: True
    _target_: trackmania_env.envs.single_agent_env2.TMNF_Single_Agent_Env

    n_previous_actions : 10

    reset_mode : "respawn"
    position_buffer_size : 20
    position_moved_threshold : 0.8

    game_speed : 20
    countdown_speed : 20

    wrap_obs_in_test : false  # Applies an test-wrapper to the observations.
    test : False

    startposition_accuracy_threshold : 0.5 # how close the start position has to be to the initial starting posiiton after each reset (in ingame-meters.)
    ignore_stuck_for_n_steps_after_reset : 80 
    automatic_prevent_sim_finish : true #If True, iface.prevent_sim_finish() is called automatically, once the current and target checkpoint are the same.
    disable_waitforstep_after_n_consecutive_timeouts : 5
    actions_per_second : 20
    waitforstep_timeout_in_s : 1.2 # this HAS to be smaller than the timeout of TMInterface
    use_rewind : True

  wrappers:
    monitor: 
      _partial_: True
      _target_: stable_baselines3.common.monitor.Monitor 

sb3:
    constructor:
      _partial_: true
      _target_: stable_baselines3.PPO
      verbose: 1 

    algorithm_params:
      #learning_rate: 0.00025          # Learning rate or scheduler function
      n_steps: 2048                  # Number of steps to run per environment per update
      batch_size: 512                 # Minibatch size for each gradient update
      n_epochs: 5                   # Number of epochs per update (how many times each minibatch is reused)
      gamma: 0.99                    # Discount factor for reward
      gae_lambda: 0.95               # Lambda for GAE (Generalized Advantage Estimation)
      clip_range: 0.2                # Clipping range for policy loss (PPO-specific)
      clip_range_vf: null            # Clipping range for value function (useful to stabilize critic updates); null means no clipping
      normalize_advantage: true      # Whether to normalize advantages before updating
      ent_coef: 0.01                  # Entropy coefficient (exploration bonus)
      vf_coef: 1                  # Value function loss coefficient
      max_grad_norm: 0.5             # Maximum gradient norm (gradient clipping)
      use_sde: false                 # Whether to use State-Dependent Exploration (for continuous actions)
      sde_sample_freq: -1           # Frequency of sampling new noise matrix for SDE (-1: only at start of episode)
      rollout_buffer_class: null     # Custom rollout buffer class (leave null to use default)
      rollout_buffer_kwargs: null    # Arguments to pass to the rollout buffer (leave null for default)
      target_kl: null                # Early stopping when approximate KL divergence reaches this value (useful for avoiding overfitting)
      stats_window_size: 100         # Window size for computing stats like average reward
      seed: null                     # Random seed (for reproducibility)
      #device: "auto"                 # Device to use: "cpu", "cuda", or "auto"
      _init_setup_model: true        # Whether to build the model immediately (usually true)

wandb_callbacks:
  _partial_: True
  _target_: wandb.integration.sb3.WandbCallback
  model_save_freq: 1000
  gradient_save_freq: 100
  log: "all"
  verbose: 2

models:
  _partial_: True
  _target_: neuronal_networks.vision_encoder.conv_NNs.VisionModelSix

lr_scheduler:
  _target_: neuronal_networks.lr_schedulers.NoScheduler
  initial_value: 2.5e-4 

policy:
  name: "basic"
  type: "MultiInputPolicy"
  extractors_out_dim: 64 # every extractor will produce an output with this dimension 
  share_features_extractor: True # whether to share the features extractor between actor and critic when applicable

extractors_out_dim: 64 # every extractor will produce an output with this dimension 
share_features_extractor: True # whether to share the features extractor between actor and critic when applicable

learn_args:
  total_timesteps: 3000000
  log_interval: 1
  reset_num_timesteps: True
  progress_bar: True
  tb_log_name: "PPO"

gmi:
  launch: True
  tm_loader_profile_name: "default"
  headless: False
  port: 8775
  track : very_long_checkpoints.Challenge.Gbx
  reference_line: tracks/reference_line/very_long_checkpoints.npy

wandb:
  use: False
  entity : tmnf-practical-ss25
  project : tmnf_ppo
  checkpoint_freq : 500000 # after how many steps should the model be saved automatically
  eval_freq : 400000 # after how many steps should we check if there is a new better model
