name: "sac_simbav2"
type: "simbav2"

policy_kwargs:
  normalized_g_max: 5

  actor_kwargs:
    num_blocks: 1
    hidden_dim: 128

    scaler_init: ${eval:'math.sqrt(2 / ${policy.policy_kwargs.actor_kwargs.hidden_dim})'}
    scaler_scale: ${eval:'math.sqrt(2 / ${policy.policy_kwargs.actor_kwargs.hidden_dim})'}

    alpha_init: ${eval:'1 / (${policy.policy_kwargs.actor_kwargs.num_blocks} + 1)'}
    alpha_scale: ${eval:'1 / math.sqrt(${policy.policy_kwargs.actor_kwargs.hidden_dim})'}

    c_shift: 3.0

  critic_kwargs:
    num_blocks: 2
    hidden_dim: 512

    scaler_init: ${eval:'math.sqrt(2 / ${policy.policy_kwargs.critic_kwargs.hidden_dim})'}
    scaler_scale: ${eval:'math.sqrt(2 / ${policy.policy_kwargs.critic_kwargs.hidden_dim})'}

    alpha_init: ${eval:'1 / (${policy.policy_kwargs.critic_kwargs.num_blocks} + 1)'}
    alpha_scale: ${eval:'1 / math.sqrt(${policy.policy_kwargs.critic_kwargs.hidden_dim})'}

    min_v: ${eval:'-${policy.policy_kwargs.normalized_g_max}'}
    max_v: ${eval:'${policy.policy_kwargs.normalized_g_max}'}

    c_shift: 3.0
    num_bins: 101
