name: "async_actor_critic"
verbose: 1

actor:
   extractors_out_dim: 64
   observations: [image,propriocentric_features]
   float_net: [2048, 2048, 2048, 2048, 4]
   activation_fn:
     _target_: torch.nn.ReLU
   last_activation_fn:
     _target_: torch.nn.Tanh

critic:
   extractors_out_dim: 64
   observations: [propriocentric_features,global_features]
   float_net: [2048, 2048, 2048, 2048, 32]
   activation_fn:
     _target_: torch.nn.ReLU
   last_activation_fn:
     _target_: torch.nn.Linear
     in_features: 32
     out_features: 64

  