_target_: trackmania_gym.trackmania_env.observations.implementations.dyn_nextpoint_obs.DynamicNextPointObsManager
name: "dyna_nextpoint"

# image related
obs_have_imgs: True
check_channels: True
img_width: 128
img_height: 128
store_imgs_as_uint8: False
norm_uint8_imgs: False
colorspace: "grayscale"
camera_id: 2

# other 
convert_torch: True

# reference line related 
n_points: 60
lookahead_sec: 6
