_target_: trackmania_env.observations.implementations.nextpoint_obs.NextPointObsManager
name: "nextpointobs"

# image related
img_width: 128
img_height: 128
colorspace: "grayscale"
camera_id: 2

# other 
convert_torch: True
