_target_: trackmania_gym.trackmania_env.observations.implementations.nextpoint_obs.NextPointObsManager
name: "nextpointobs"

# image related
obs_have_imgs: True
check_channels: False
img_width: 128
img_height: 128
store_imgs_as_uint8: False
norm_uint8_imgs: False
colorspace: "grayscale"
camera_id: 2

# other 
convert_torch: True
