_target_: trackmania_env.observations.implementations.sophy_obs.SophyObsManager
name: "sophy"

# image related
img_width: 64
img_height: 64
store_imgs_as_uint8: True
norm_uint8_imgs: False
colorspace: "rgb"
camera_id: 3

# reference line related 
n_points: 60
lookahead_sec: 6

# other 
maxlen_history: 3
convert_torch: True
