from gymnasium.spaces import Box,Discrete,Dict 
from numpy import uint8,int32,int64,float32,inf
simstate_space_dict = {
    "cmd_buffer_core": Box(-9223372036854775808, 9223372036854775807, (264,), int64),
    "cmd_buffer_core_field": Box(0, 255, (264,), uint8),
    "context_mode": Box(-inf, inf, (), float32),
    "context_mode_field": Box(-2147483648, 2147483647, (), int32),
    #"cp_data.cp_states": Box([], [], (0,), bool),
    "cp_data.cp_states_length": Box(-inf, inf, (), float32),
    "cp_data.cp_states_length_field": Box(-2147483648, 2147483647, (), int32),
    "cp_data.cp_times_length": Box(-inf, inf, (), float32),
    "cp_data.cp_times_length_field": Box(-2147483648, 2147483647, (), int32),
    "cp_data.data": Box(-inf, inf, (12,), float32),
    "cp_data.master_offset": Box(-inf, inf, (), float32),
    "cp_data.min_size": Box(-inf, inf, (), float32),
    "cp_data.reserved": Box(-inf, inf, (), float32),
    "cp_data.reserved_field": Box(-2147483648, 2147483647, (), int32),
    "cp_data.size": Box(-inf, inf, (), float32),
    "data": Box(-inf, inf, (8356,), float32),
    "display_speed": Box(-inf, inf, (), float32),
    "dyna.current_state.add_linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.current_state.angular_speed": Box(-inf, inf, (3,), float32),
    "dyna.current_state.data": Box(-inf, inf, (180,), float32),
    "dyna.current_state.force": Box(-inf, inf, (3,), float32),
    "dyna.current_state.inverse_inertia_tensor": Box(-inf, inf, (3, 3), float32),
    "dyna.current_state.inverse_intertia_tensor": Box(-inf, inf, (3, 3), float32),
    "dyna.current_state.linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.current_state.master_offset": Box(-inf, inf, (), float32),
    "dyna.current_state.min_size": Box(-inf, inf, (), float32),
    "dyna.current_state.not_tweaked_linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.current_state.owner": Box(-inf, inf, (), float32),
    "dyna.current_state.owner_field": Box(-2147483648, 2147483647, (), int32),
    "dyna.current_state.position": Box(-inf, inf, (3,), float32),
    "dyna.current_state.quat": Box(-inf, inf, (4,), float32),
    "dyna.current_state.rotation": Box(-inf, inf, (3, 3), float32),
    "dyna.current_state.size": Box(-inf, inf, (), float32),
    "dyna.current_state.torque": Box(-inf, inf, (3,), float32),
    "dyna.current_state.unknown": Box(-inf, inf, (), float32),
    "dyna.current_state.unknown_field": Box(-inf, inf, (), float32),
    "dyna.data": Box(-inf, inf, (1424,), float32),
    "dyna.master_offset": Box(-inf, inf, (), float32),
    "dyna.min_size": Box(-inf, inf, (), float32),
    "dyna.prev_state.add_linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.prev_state.angular_speed": Box(-inf, inf, (3,), float32),
    "dyna.prev_state.data": Box(-inf, inf, (180,), float32),
    "dyna.prev_state.force": Box(-inf, inf, (3,), float32),
    "dyna.prev_state.inverse_inertia_tensor": Box(-inf, inf, (3, 3), float32),
    "dyna.prev_state.inverse_intertia_tensor": Box(-inf, inf, (3, 3), float32),
    "dyna.prev_state.linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.prev_state.master_offset": Box(-inf, inf, (), float32),
    "dyna.prev_state.min_size": Box(-inf, inf, (), float32),
    "dyna.prev_state.not_tweaked_linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.prev_state.owner": Box(-inf, inf, (), float32),
    "dyna.prev_state.owner_field": Box(-2147483648, 2147483647, (), int32),
    "dyna.prev_state.position": Box(-inf, inf, (3,), float32),
    "dyna.prev_state.quat": Box(-inf, inf, (4,), float32),
    "dyna.prev_state.rotation": Box(-inf, inf, (3, 3), float32),
    "dyna.prev_state.size": Box(-inf, inf, (), float32),
    "dyna.prev_state.torque": Box(-inf, inf, (3,), float32),
    "dyna.prev_state.unknown": Box(-inf, inf, (), float32),
    "dyna.prev_state.unknown_field": Box(-inf, inf, (), float32),
    "dyna.previous_state.add_linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.previous_state.angular_speed": Box(-inf, inf, (3,), float32),
    "dyna.previous_state.data": Box(-inf, inf, (180,), float32),
    "dyna.previous_state.force": Box(-inf, inf, (3,), float32),
    "dyna.previous_state.inverse_inertia_tensor": Box(-inf, inf, (3, 3), float32),
    "dyna.previous_state.inverse_intertia_tensor": Box(-inf, inf, (3, 3), float32),
    "dyna.previous_state.linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.previous_state.master_offset": Box(-inf, inf, (), float32),
    "dyna.previous_state.min_size": Box(-inf, inf, (), float32),
    "dyna.previous_state.not_tweaked_linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.previous_state.owner": Box(-inf, inf, (), float32),
    "dyna.previous_state.owner_field": Box(-2147483648, 2147483647, (), int32),
    "dyna.previous_state.position": Box(-inf, inf, (3,), float32),
    "dyna.previous_state.quat": Box(-inf, inf, (4,), float32),
    "dyna.previous_state.rotation": Box(-inf, inf, (3, 3), float32),
    "dyna.previous_state.size": Box(-inf, inf, (), float32),
    "dyna.previous_state.torque": Box(-inf, inf, (3,), float32),
    "dyna.previous_state.unknown": Box(-inf, inf, (), float32),
    "dyna.previous_state.unknown_field": Box(-inf, inf, (), float32),
    "dyna.rest": Box(-9223372036854775808, 9223372036854775807, (616,), int64),
    "dyna.rest_field": Box(0, 255, (616,), uint8),
    "dyna.size": Box(-inf, inf, (), float32),
    "dyna.temp_state.add_linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.temp_state.angular_speed": Box(-inf, inf, (3,), float32),
    "dyna.temp_state.data": Box(-inf, inf, (180,), float32),
    "dyna.temp_state.force": Box(-inf, inf, (3,), float32),
    "dyna.temp_state.inverse_inertia_tensor": Box(-inf, inf, (3, 3), float32),
    "dyna.temp_state.inverse_intertia_tensor": Box(-inf, inf, (3, 3), float32),
    "dyna.temp_state.linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.temp_state.master_offset": Box(-inf, inf, (), float32),
    "dyna.temp_state.min_size": Box(-inf, inf, (), float32),
    "dyna.temp_state.not_tweaked_linear_speed": Box(-inf, inf, (3,), float32),
    "dyna.temp_state.owner": Box(-inf, inf, (), float32),
    "dyna.temp_state.owner_field": Box(-2147483648, 2147483647, (), int32),
    "dyna.temp_state.position": Box(-inf, inf, (3,), float32),
    "dyna.temp_state.quat": Box(-inf, inf, (4,), float32),
    "dyna.temp_state.rotation": Box(-inf, inf, (3, 3), float32),
    "dyna.temp_state.size": Box(-inf, inf, (), float32),
    "dyna.temp_state.torque": Box(-inf, inf, (3,), float32),
    "dyna.temp_state.unknown": Box(-inf, inf, (), float32),
    "dyna.temp_state.unknown_field": Box(-inf, inf, (), float32),
    "flags": Box(-inf, inf, (), float32),
    "flags_field": Box(-2147483648, 2147483647, (), int32),
    "input_accelerate": Box(-inf, inf, (), float32),
    "input_accelerate_event.binary_value": Box(-inf, inf, (), float32),
    "input_accelerate_event.data": Box(-inf, inf, (8,), float32),
    "input_accelerate_event.input_data": Box(-inf, inf, (), float32),
    "input_accelerate_event.input_data_field": Box(-2147483648, 2147483647, (), int32),
    "input_accelerate_event.master_offset": Box(-inf, inf, (), float32),
    "input_accelerate_event.min_size": Box(-inf, inf, (), float32),
    "input_accelerate_event.name_index": Box(-inf, inf, (), float32),
    "input_accelerate_event.size": Box(-inf, inf, (), float32),
    "input_accelerate_event.time": Box(-inf, inf, (), float32),
    "input_accelerate_event.time_field": Box(-2147483648, 2147483647, (), int32),
    "input_brake": Box(-inf, inf, (), float32),
    "input_brake_event.binary_value": Box(-inf, inf, (), float32),
    "input_brake_event.data": Box(-inf, inf, (8,), float32),
    "input_brake_event.input_data": Box(-inf, inf, (), float32),
    "input_brake_event.input_data_field": Box(-2147483648, 2147483647, (), int32),
    "input_brake_event.master_offset": Box(-inf, inf, (), float32),
    "input_brake_event.min_size": Box(-inf, inf, (), float32),
    "input_brake_event.name_index": Box(-inf, inf, (), float32),
    "input_brake_event.size": Box(-inf, inf, (), float32),
    "input_brake_event.time": Box(-inf, inf, (), float32),
    "input_brake_event.time_field": Box(-2147483648, 2147483647, (), int32),
    "input_finish_event.binary_value": Box(-inf, inf, (), float32),
    "input_finish_event.data": Box(-inf, inf, (8,), float32),
    "input_finish_event.input_data": Box(-inf, inf, (), float32),
    "input_finish_event.input_data_field": Box(-2147483648, 2147483647, (), int32),
    "input_finish_event.master_offset": Box(-inf, inf, (), float32),
    "input_finish_event.min_size": Box(-inf, inf, (), float32),
    "input_finish_event.name_index": Box(-inf, inf, (), float32),
    "input_finish_event.size": Box(-inf, inf, (), float32),
    "input_finish_event.time": Box(-inf, inf, (), float32),
    "input_finish_event.time_field": Box(-2147483648, 2147483647, (), int32),
    "input_gas_event.binary_value": Box(-inf, inf, (), float32),
    "input_gas_event.data": Box(-inf, inf, (8,), float32),
    "input_gas_event.input_data": Box(-inf, inf, (), float32),
    "input_gas_event.input_data_field": Box(-2147483648, 2147483647, (), int32),
    "input_gas_event.master_offset": Box(-inf, inf, (), float32),
    "input_gas_event.min_size": Box(-inf, inf, (), float32),
    "input_gas_event.name_index": Box(-inf, inf, (), float32),
    "input_gas_event.size": Box(-inf, inf, (), float32),
    "input_gas_event.time": Box(-inf, inf, (), float32),
    "input_gas_event.time_field": Box(-2147483648, 2147483647, (), int32),
    "input_left": Box(-inf, inf, (), float32),
    "input_left_event.binary_value": Box(-inf, inf, (), float32),
    "input_left_event.data": Box(-inf, inf, (8,), float32),
    "input_left_event.input_data": Box(-inf, inf, (), float32),
    "input_left_event.input_data_field": Box(-2147483648, 2147483647, (), int32),
    "input_left_event.master_offset": Box(-inf, inf, (), float32),
    "input_left_event.min_size": Box(-inf, inf, (), float32),
    "input_left_event.name_index": Box(-inf, inf, (), float32),
    "input_left_event.size": Box(-inf, inf, (), float32),
    "input_left_event.time": Box(-inf, inf, (), float32),
    "input_left_event.time_field": Box(-2147483648, 2147483647, (), int32),
    "input_right": Box(-inf, inf, (), float32),
    "input_right_event.binary_value": Box(-inf, inf, (), float32),
    "input_right_event.data": Box(-inf, inf, (8,), float32),
    "input_right_event.input_data": Box(-inf, inf, (), float32),
    "input_right_event.input_data_field": Box(-2147483648, 2147483647, (), int32),
    "input_right_event.master_offset": Box(-inf, inf, (), float32),
    "input_right_event.min_size": Box(-inf, inf, (), float32),
    "input_right_event.name_index": Box(-inf, inf, (), float32),
    "input_right_event.size": Box(-inf, inf, (), float32),
    "input_right_event.time": Box(-inf, inf, (), float32),
    "input_right_event.time_field": Box(-2147483648, 2147483647, (), int32),
    "input_running_event.binary_value": Box(-inf, inf, (), float32),
    "input_running_event.data": Box(-inf, inf, (8,), float32),
    "input_running_event.input_data": Box(-inf, inf, (), float32),
    "input_running_event.input_data_field": Box(-2147483648, 2147483647, (), int32),
    "input_running_event.master_offset": Box(-inf, inf, (), float32),
    "input_running_event.min_size": Box(-inf, inf, (), float32),
    "input_running_event.name_index": Box(-inf, inf, (), float32),
    "input_running_event.size": Box(-inf, inf, (), float32),
    "input_running_event.time": Box(-inf, inf, (), float32),
    "input_running_event.time_field": Box(-2147483648, 2147483647, (), int32),
    "input_steer_event.binary_value": Box(-inf, inf, (), float32),
    "input_steer_event.data": Box(-inf, inf, (8,), float32),
    "input_steer_event.input_data": Box(-inf, inf, (), float32),
    "input_steer_event.input_data_field": Box(-2147483648, 2147483647, (), int32),
    "input_steer_event.master_offset": Box(-inf, inf, (), float32),
    "input_steer_event.min_size": Box(-inf, inf, (), float32),
    "input_steer_event.name_index": Box(-inf, inf, (), float32),
    "input_steer_event.size": Box(-inf, inf, (), float32),
    "input_steer_event.time": Box(-inf, inf, (), float32),
    "master_offset": Box(-inf, inf, (), float32),
    "min_size": Box(-inf, inf, (), float32),
    "num_respawns": Box(-inf, inf, (), float32),
    "num_respawns_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.average_rank": Box(-inf, inf, (), float32),
    "player_info.average_rank_field": Box(-inf, inf, (), float32),
    "player_info.best_stunts_score": Box(-inf, inf, (), float32),
    "player_info.best_stunts_score_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.countdown_time": Box(-inf, inf, (), float32),
    "player_info.countdown_time_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.cur_checkpoint": Box(-inf, inf, (), float32),
    "player_info.cur_checkpoint_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.cur_cp_count": Box(-inf, inf, (), float32),
    "player_info.cur_cp_count_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.cur_lap": Box(-inf, inf, (), float32),
    "player_info.cur_lap_cp_count": Box(-inf, inf, (), float32),
    "player_info.cur_lap_cp_count_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.cur_lap_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.current_race_rank": Box(-inf, inf, (), float32),
    "player_info.current_race_rank_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.current_round_rank": Box(-inf, inf, (), float32),
    "player_info.current_round_rank_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.current_time": Box(-inf, inf, (), float32),
    "player_info.current_time_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.data": Box(-inf, inf, (952,), float32),
    "player_info.display_speed": Box(-inf, inf, (), float32),
    "player_info.display_speed_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.finish_not_passed": Box(-inf, inf, (), float32),
    "player_info.finish_not_passed_field": Discrete(2),
    "player_info.lap_best_time": Box(-inf, inf, (), float32),
    "player_info.lap_best_time_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.lap_start_time": Box(-inf, inf, (), float32),
    "player_info.lap_start_time_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.lap_time": Box(-inf, inf, (), float32),
    "player_info.lap_time_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.master_offset": Box(-inf, inf, (), float32),
    "player_info.max_completed": Box(-inf, inf, (), float32),
    "player_info.max_completed_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.min_respawns": Box(-inf, inf, (), float32),
    "player_info.min_respawns_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.min_size": Box(-inf, inf, (), float32),
    "player_info.nb_completed": Box(-inf, inf, (), float32),
    "player_info.nb_completed_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.offset_current_cp": Box(-inf, inf, (), float32),
    "player_info.offset_current_cp_field": Box(-inf, inf, (), float32),
    "player_info.prev_race_time": Box(-inf, inf, (), float32),
    "player_info.prev_race_time_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.race_best_time": Box(-inf, inf, (), float32),
    "player_info.race_best_time_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.race_finished": Box(-inf, inf, (), float32),
    "player_info.race_finished_field": Discrete(2),
    "player_info.race_start_time": Box(-inf, inf, (), float32),
    "player_info.race_start_time_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.race_state": Box(-inf, inf, (), float32),
    "player_info.race_state_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.race_time": Box(-inf, inf, (), float32),
    "player_info.race_time_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.ready_enum": Box(-inf, inf, (), float32),
    "player_info.ready_enum_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.rest": Box(-9223372036854775808, 9223372036854775807, (32,), int64),
    "player_info.rest_field": Box(0, 255, (32,), uint8),
    "player_info.round_num": Box(-inf, inf, (), float32),
    "player_info.round_num_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.size": Box(-inf, inf, (), float32),
    "player_info.stunts_score": Box(-inf, inf, (), float32),
    "player_info.stunts_score_field": Box(-2147483648, 2147483647, (), int32),
    "player_info.team": Box(-inf, inf, (), float32),
    "player_info.team_field": Box(-2147483648, 2147483647, (), int32),
    "plug_solid": Box(-9223372036854775808, 9223372036854775807, (68,), int64),
    "plug_solid_field": Box(0, 255, (68,), uint8),
    "position": Box(-inf, inf, (3,), float32),
    "race_time": Box(-inf, inf, (), float32),
    "rewind_time": Box(-inf, inf, (), float32),
    "rotation_matrix": Box(-inf, inf, (3, 3), float32),
    "scene_mobil.async_vehicle_state.data": Box(-inf, inf, (168,), float32),
    "scene_mobil.async_vehicle_state.gearbox_state": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.gearbox_state_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.async_vehicle_state.input_brake": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.input_brake_field": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.input_gas": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.input_gas_field": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.input_steer": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.input_steer_field": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.is_turbo": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.is_turbo_field": Discrete(2),
    "scene_mobil.async_vehicle_state.master_offset": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.min_size": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.rest": Box(-9223372036854775808, 9223372036854775807, (28,), int64),
    "scene_mobil.async_vehicle_state.rest_field": Box(0, 255, (28,), uint8),
    "scene_mobil.async_vehicle_state.rpm": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.rpm_field": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.size": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.speed_forward": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.speed_forward_field": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.speed_sideward": Box(-inf, inf, (), float32),
    "scene_mobil.async_vehicle_state.speed_sideward_field": Box(-inf, inf, (), float32),
    "scene_mobil.block_flags": Box(-inf, inf, (), float32),
    "scene_mobil.block_flags_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.burnout_state": Box(-inf, inf, (), float32),
    "scene_mobil.burnout_state_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.current_local_speed": Box(-inf, inf, (3,), float32),
    "scene_mobil.data": Box(-inf, inf, (2168,), float32),
    "scene_mobil.engine.actual_rpm": Box(-inf, inf, (), float32),
    "scene_mobil.engine.actual_rpm_field": Box(-inf, inf, (), float32),
    "scene_mobil.engine.braking_factor": Box(-inf, inf, (), float32),
    "scene_mobil.engine.braking_factor_field": Box(-inf, inf, (), float32),
    "scene_mobil.engine.clamped_rpm": Box(-inf, inf, (), float32),
    "scene_mobil.engine.clamped_rpm_field": Box(-inf, inf, (), float32),
    "scene_mobil.engine.data": Box(-inf, inf, (48,), float32),
    "scene_mobil.engine.gear": Box(-inf, inf, (), float32),
    "scene_mobil.engine.gear_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.engine.master_offset": Box(-inf, inf, (), float32),
    "scene_mobil.engine.max_rpm": Box(-inf, inf, (), float32),
    "scene_mobil.engine.max_rpm_field": Box(-inf, inf, (), float32),
    "scene_mobil.engine.min_size": Box(-inf, inf, (), float32),
    "scene_mobil.engine.rear_gear": Box(-inf, inf, (), float32),
    "scene_mobil.engine.rear_gear_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.engine.size": Box(-inf, inf, (), float32),
    "scene_mobil.engine.slide_factor": Box(-inf, inf, (), float32),
    "scene_mobil.engine.slide_factor_field": Box(-inf, inf, (), float32),
    "scene_mobil.gearbox_state": Box(-inf, inf, (), float32),
    "scene_mobil.gearbox_state_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.has_any_lateral_contact": Box(-inf, inf, (), float32),
    "scene_mobil.has_any_lateral_contact_field": Discrete(2),
    "scene_mobil.horn_limit": Box(-inf, inf, (), float32),
    "scene_mobil.horn_limit_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.input_brake": Box(-inf, inf, (), float32),
    "scene_mobil.input_brake_field": Box(-inf, inf, (), float32),
    "scene_mobil.input_gas": Box(-inf, inf, (), float32),
    "scene_mobil.input_gas_field": Box(-inf, inf, (), float32),
    "scene_mobil.input_steer": Box(-inf, inf, (), float32),
    "scene_mobil.input_steer_field": Box(-inf, inf, (), float32),
    "scene_mobil.is_freewheeling": Box(-inf, inf, (), float32),
    "scene_mobil.is_freewheeling_field": Discrete(2),
    "scene_mobil.is_light_trials_set": Box(-inf, inf, (), float32),
    "scene_mobil.is_light_trials_set_field": Discrete(2),
    "scene_mobil.is_rubber_ball": Box(-inf, inf, (), float32),
    "scene_mobil.is_rubber_ball_field": Discrete(2),
    "scene_mobil.is_sliding": Box(-inf, inf, (), float32),
    "scene_mobil.is_sliding_field": Discrete(2),
    "scene_mobil.is_update_async": Box(-inf, inf, (), float32),
    "scene_mobil.is_update_async_field": Discrete(2),
    "scene_mobil.last_has_any_lateral_contact_time": Box(-inf, inf, (), float32),
    "scene_mobil.last_has_any_lateral_contact_time_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.last_turbo_time": Box(-inf, inf, (), float32),
    "scene_mobil.last_turbo_time_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.last_turbo_type_change_time": Box(-inf, inf, (), float32),
    "scene_mobil.last_turbo_type_change_time_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.master_offset": Box(-inf, inf, (), float32),
    "scene_mobil.max_linear_speed": Box(-inf, inf, (), float32),
    "scene_mobil.max_linear_speed_field": Box(-inf, inf, (), float32),
    "scene_mobil.min_size": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.data": Box(-inf, inf, (168,), float32),
    "scene_mobil.prev_async_vehicle_state.gearbox_state": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.gearbox_state_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.prev_async_vehicle_state.input_brake": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.input_brake_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.input_gas": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.input_gas_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.input_steer": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.input_steer_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.is_turbo": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.is_turbo_field": Discrete(2),
    "scene_mobil.prev_async_vehicle_state.master_offset": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.min_size": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.rest": Box(-9223372036854775808, 9223372036854775807, (28,), int64),
    "scene_mobil.prev_async_vehicle_state.rest_field": Box(0, 255, (28,), uint8),
    "scene_mobil.prev_async_vehicle_state.rpm": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.rpm_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.size": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.speed_forward": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.speed_forward_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.speed_sideward": Box(-inf, inf, (), float32),
    "scene_mobil.prev_async_vehicle_state.speed_sideward_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.data": Box(-inf, inf, (168,), float32),
    "scene_mobil.prev_sync_vehicle_state.gearbox_state": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.gearbox_state_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.prev_sync_vehicle_state.input_brake": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.input_brake_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.input_gas": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.input_gas_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.input_steer": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.input_steer_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.is_turbo": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.is_turbo_field": Discrete(2),
    "scene_mobil.prev_sync_vehicle_state.master_offset": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.min_size": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.rest": Box(-9223372036854775808, 9223372036854775807, (28,), int64),
    "scene_mobil.prev_sync_vehicle_state.rest_field": Box(0, 255, (28,), uint8),
    "scene_mobil.prev_sync_vehicle_state.rpm": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.rpm_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.size": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.speed_forward": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.speed_forward_field": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.speed_sideward": Box(-inf, inf, (), float32),
    "scene_mobil.prev_sync_vehicle_state.speed_sideward_field": Box(-inf, inf, (), float32),
    "scene_mobil.quality": Box(-inf, inf, (), float32),
    "scene_mobil.quality_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.roulette_value": Box(-inf, inf, (), float32),
    "scene_mobil.roulette_value_field": Box(-inf, inf, (), float32),
    "scene_mobil.saved_state": Box(-inf, inf, (4, 3), float32),
    "scene_mobil.size": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.data": Box(-inf, inf, (168,), float32),
    "scene_mobil.sync_vehicle_state.gearbox_state": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.gearbox_state_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.sync_vehicle_state.input_brake": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.input_brake_field": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.input_gas": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.input_gas_field": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.input_steer": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.input_steer_field": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.is_turbo": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.is_turbo_field": Discrete(2),
    "scene_mobil.sync_vehicle_state.master_offset": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.min_size": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.rest": Box(-9223372036854775808, 9223372036854775807, (28,), int64),
    "scene_mobil.sync_vehicle_state.rest_field": Box(0, 255, (28,), uint8),
    "scene_mobil.sync_vehicle_state.rpm": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.rpm_field": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.size": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.speed_forward": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.speed_forward_field": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.speed_sideward": Box(-inf, inf, (), float32),
    "scene_mobil.sync_vehicle_state.speed_sideward_field": Box(-inf, inf, (), float32),
    "scene_mobil.total_central_force_added": Box(-inf, inf, (3,), float32),
    "scene_mobil.turbo_boost_factor": Box(-inf, inf, (), float32),
    "scene_mobil.turbo_boost_factor_field": Box(-inf, inf, (), float32),
    "scene_mobil.turbo_type": Box(-inf, inf, (), float32),
    "scene_mobil.turbo_type_field": Box(-2147483648, 2147483647, (), int32),
    "scene_mobil.turning_rate": Box(-inf, inf, (), float32),
    "scene_mobil.turning_rate_field": Box(-inf, inf, (), float32),
    "scene_mobil.water_forces_applied": Box(-inf, inf, (), float32),
    "scene_mobil.water_forces_applied_field": Discrete(2),
    "scene_mobil.wheel_contact_absorb_counter": Box(-inf, inf, (), float32),
    "scene_mobil.wheel_contact_absorb_counter_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[0].async_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[0].async_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[0].async_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].async_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[0].async_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[0].async_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].contact_relative_local_distance": Box(-inf, inf, (3,), float32),
    "simulation_wheels[0].data": Box(-inf, inf, (764,), float32),
    "simulation_wheels[0].field_112": Box(-inf, inf, (4, 3), float32),
    "simulation_wheels[0].field_160": Box(-inf, inf, (), float32),
    "simulation_wheels[0].field_160_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[0].field_164": Box(-inf, inf, (), float32),
    "simulation_wheels[0].field_164_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[0].field_348": Box(-inf, inf, (), float32),
    "simulation_wheels[0].field_348_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[0].field_564.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[0].field_564.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[0].field_564.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].field_564.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[0].field_564.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[0].field_564.size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].field_8": Box(-inf, inf, (), float32),
    "simulation_wheels[0].field_8_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[0].master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[0].min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].offset_from_vehicle": Box(-inf, inf, (3,), float32),
    "simulation_wheels[0].prev_sync_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[0].prev_sync_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[0].prev_sync_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].prev_sync_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[0].prev_sync_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[0].prev_sync_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.contact_material_id": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.contact_material_id_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[0].real_time_state.damper_absorb": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.damper_absorb_field": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.data": Box(-inf, inf, (168,), float32),
    "simulation_wheels[0].real_time_state.field_108": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.field_108_field": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.field_12": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[0].real_time_state.field_144": Box(-inf, inf, (3,), float32),
    "simulation_wheels[0].real_time_state.field_4": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.field_48": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[0].real_time_state.field_4_field": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.field_8": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.field_84": Box(-inf, inf, (3,), float32),
    "simulation_wheels[0].real_time_state.field_8_field": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.has_ground_contact": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.has_ground_contact_field": Discrete(2),
    "simulation_wheels[0].real_time_state.is_sliding": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.is_sliding_field": Discrete(2),
    "simulation_wheels[0].real_time_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.nb_ground_contacts": Box(-inf, inf, (), float32),
    "simulation_wheels[0].real_time_state.nb_ground_contacts_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[0].real_time_state.relative_rotz_axis": Box(-inf, inf, (3,), float32),
    "simulation_wheels[0].real_time_state.rest": Box(-9223372036854775808, 9223372036854775807, (12,), int64),
    "simulation_wheels[0].real_time_state.rest_field": Box(0, 255, (12,), uint8),
    "simulation_wheels[0].real_time_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].steerable": Box(-inf, inf, (), float32),
    "simulation_wheels[0].steerable_field": Discrete(2),
    "simulation_wheels[0].surface_handler.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[0].surface_handler.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[0].surface_handler.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].surface_handler.position": Box(-inf, inf, (3,), float32),
    "simulation_wheels[0].surface_handler.rotation": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[0].surface_handler.size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].surface_handler.unknown": Box(-inf, inf, (4, 3), float32),
    "simulation_wheels[0].sync_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[0].sync_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[0].sync_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[0].sync_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[0].sync_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[0].sync_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].async_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[1].async_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[1].async_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].async_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[1].async_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[1].async_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].contact_relative_local_distance": Box(-inf, inf, (3,), float32),
    "simulation_wheels[1].data": Box(-inf, inf, (764,), float32),
    "simulation_wheels[1].field_112": Box(-inf, inf, (4, 3), float32),
    "simulation_wheels[1].field_160": Box(-inf, inf, (), float32),
    "simulation_wheels[1].field_160_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[1].field_164": Box(-inf, inf, (), float32),
    "simulation_wheels[1].field_164_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[1].field_348": Box(-inf, inf, (), float32),
    "simulation_wheels[1].field_348_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[1].field_564.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[1].field_564.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[1].field_564.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].field_564.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[1].field_564.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[1].field_564.size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].field_8": Box(-inf, inf, (), float32),
    "simulation_wheels[1].field_8_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[1].master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[1].min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].offset_from_vehicle": Box(-inf, inf, (3,), float32),
    "simulation_wheels[1].prev_sync_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[1].prev_sync_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[1].prev_sync_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].prev_sync_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[1].prev_sync_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[1].prev_sync_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.contact_material_id": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.contact_material_id_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[1].real_time_state.damper_absorb": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.damper_absorb_field": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.data": Box(-inf, inf, (168,), float32),
    "simulation_wheels[1].real_time_state.field_108": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.field_108_field": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.field_12": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[1].real_time_state.field_144": Box(-inf, inf, (3,), float32),
    "simulation_wheels[1].real_time_state.field_4": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.field_48": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[1].real_time_state.field_4_field": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.field_8": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.field_84": Box(-inf, inf, (3,), float32),
    "simulation_wheels[1].real_time_state.field_8_field": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.has_ground_contact": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.has_ground_contact_field": Discrete(2),
    "simulation_wheels[1].real_time_state.is_sliding": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.is_sliding_field": Discrete(2),
    "simulation_wheels[1].real_time_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.nb_ground_contacts": Box(-inf, inf, (), float32),
    "simulation_wheels[1].real_time_state.nb_ground_contacts_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[1].real_time_state.relative_rotz_axis": Box(-inf, inf, (3,), float32),
    "simulation_wheels[1].real_time_state.rest": Box(-9223372036854775808, 9223372036854775807, (12,), int64),
    "simulation_wheels[1].real_time_state.rest_field": Box(0, 255, (12,), uint8),
    "simulation_wheels[1].real_time_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].steerable": Box(-inf, inf, (), float32),
    "simulation_wheels[1].steerable_field": Discrete(2),
    "simulation_wheels[1].surface_handler.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[1].surface_handler.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[1].surface_handler.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].surface_handler.position": Box(-inf, inf, (3,), float32),
    "simulation_wheels[1].surface_handler.rotation": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[1].surface_handler.size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].surface_handler.unknown": Box(-inf, inf, (4, 3), float32),
    "simulation_wheels[1].sync_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[1].sync_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[1].sync_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[1].sync_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[1].sync_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[1].sync_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].async_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[2].async_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[2].async_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].async_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[2].async_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[2].async_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].contact_relative_local_distance": Box(-inf, inf, (3,), float32),
    "simulation_wheels[2].data": Box(-inf, inf, (764,), float32),
    "simulation_wheels[2].field_112": Box(-inf, inf, (4, 3), float32),
    "simulation_wheels[2].field_160": Box(-inf, inf, (), float32),
    "simulation_wheels[2].field_160_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[2].field_164": Box(-inf, inf, (), float32),
    "simulation_wheels[2].field_164_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[2].field_348": Box(-inf, inf, (), float32),
    "simulation_wheels[2].field_348_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[2].field_564.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[2].field_564.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[2].field_564.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].field_564.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[2].field_564.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[2].field_564.size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].field_8": Box(-inf, inf, (), float32),
    "simulation_wheels[2].field_8_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[2].master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[2].min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].offset_from_vehicle": Box(-inf, inf, (3,), float32),
    "simulation_wheels[2].prev_sync_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[2].prev_sync_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[2].prev_sync_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].prev_sync_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[2].prev_sync_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[2].prev_sync_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.contact_material_id": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.contact_material_id_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[2].real_time_state.damper_absorb": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.damper_absorb_field": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.data": Box(-inf, inf, (168,), float32),
    "simulation_wheels[2].real_time_state.field_108": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.field_108_field": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.field_12": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[2].real_time_state.field_144": Box(-inf, inf, (3,), float32),
    "simulation_wheels[2].real_time_state.field_4": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.field_48": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[2].real_time_state.field_4_field": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.field_8": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.field_84": Box(-inf, inf, (3,), float32),
    "simulation_wheels[2].real_time_state.field_8_field": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.has_ground_contact": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.has_ground_contact_field": Discrete(2),
    "simulation_wheels[2].real_time_state.is_sliding": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.is_sliding_field": Discrete(2),
    "simulation_wheels[2].real_time_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.nb_ground_contacts": Box(-inf, inf, (), float32),
    "simulation_wheels[2].real_time_state.nb_ground_contacts_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[2].real_time_state.relative_rotz_axis": Box(-inf, inf, (3,), float32),
    "simulation_wheels[2].real_time_state.rest": Box(-9223372036854775808, 9223372036854775807, (12,), int64),
    "simulation_wheels[2].real_time_state.rest_field": Box(0, 255, (12,), uint8),
    "simulation_wheels[2].real_time_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].steerable": Box(-inf, inf, (), float32),
    "simulation_wheels[2].steerable_field": Discrete(2),
    "simulation_wheels[2].surface_handler.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[2].surface_handler.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[2].surface_handler.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].surface_handler.position": Box(-inf, inf, (3,), float32),
    "simulation_wheels[2].surface_handler.rotation": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[2].surface_handler.size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].surface_handler.unknown": Box(-inf, inf, (4, 3), float32),
    "simulation_wheels[2].sync_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[2].sync_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[2].sync_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[2].sync_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[2].sync_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[2].sync_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].async_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[3].async_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[3].async_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].async_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[3].async_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[3].async_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].contact_relative_local_distance": Box(-inf, inf, (3,), float32),
    "simulation_wheels[3].data": Box(-inf, inf, (764,), float32),
    "simulation_wheels[3].field_112": Box(-inf, inf, (4, 3), float32),
    "simulation_wheels[3].field_160": Box(-inf, inf, (), float32),
    "simulation_wheels[3].field_160_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[3].field_164": Box(-inf, inf, (), float32),
    "simulation_wheels[3].field_164_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[3].field_348": Box(-inf, inf, (), float32),
    "simulation_wheels[3].field_348_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[3].field_564.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[3].field_564.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[3].field_564.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].field_564.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[3].field_564.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[3].field_564.size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].field_8": Box(-inf, inf, (), float32),
    "simulation_wheels[3].field_8_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[3].master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[3].min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].offset_from_vehicle": Box(-inf, inf, (3,), float32),
    "simulation_wheels[3].prev_sync_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[3].prev_sync_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[3].prev_sync_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].prev_sync_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[3].prev_sync_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[3].prev_sync_wheel_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.contact_material_id": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.contact_material_id_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[3].real_time_state.damper_absorb": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.damper_absorb_field": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.data": Box(-inf, inf, (168,), float32),
    "simulation_wheels[3].real_time_state.field_108": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.field_108_field": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.field_12": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[3].real_time_state.field_144": Box(-inf, inf, (3,), float32),
    "simulation_wheels[3].real_time_state.field_4": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.field_48": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[3].real_time_state.field_4_field": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.field_8": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.field_84": Box(-inf, inf, (3,), float32),
    "simulation_wheels[3].real_time_state.field_8_field": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.has_ground_contact": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.has_ground_contact_field": Discrete(2),
    "simulation_wheels[3].real_time_state.is_sliding": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.is_sliding_field": Discrete(2),
    "simulation_wheels[3].real_time_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.nb_ground_contacts": Box(-inf, inf, (), float32),
    "simulation_wheels[3].real_time_state.nb_ground_contacts_field": Box(-2147483648, 2147483647, (), int32),
    "simulation_wheels[3].real_time_state.relative_rotz_axis": Box(-inf, inf, (3,), float32),
    "simulation_wheels[3].real_time_state.rest": Box(-9223372036854775808, 9223372036854775807, (12,), int64),
    "simulation_wheels[3].real_time_state.rest_field": Box(0, 255, (12,), uint8),
    "simulation_wheels[3].real_time_state.size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].steerable": Box(-inf, inf, (), float32),
    "simulation_wheels[3].steerable_field": Discrete(2),
    "simulation_wheels[3].surface_handler.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[3].surface_handler.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[3].surface_handler.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].surface_handler.position": Box(-inf, inf, (3,), float32),
    "simulation_wheels[3].surface_handler.rotation": Box(-inf, inf, (3, 3), float32),
    "simulation_wheels[3].surface_handler.size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].surface_handler.unknown": Box(-inf, inf, (4, 3), float32),
    "simulation_wheels[3].sync_wheel_state.data": Box(-inf, inf, (100,), float32),
    "simulation_wheels[3].sync_wheel_state.master_offset": Box(-inf, inf, (), float32),
    "simulation_wheels[3].sync_wheel_state.min_size": Box(-inf, inf, (), float32),
    "simulation_wheels[3].sync_wheel_state.rest": Box(-9223372036854775808, 9223372036854775807, (100,), int64),
    "simulation_wheels[3].sync_wheel_state.rest_field": Box(0, 255, (100,), uint8),
    "simulation_wheels[3].sync_wheel_state.size": Box(-inf, inf, (), float32),
    "size": Box(-inf, inf, (), float32),
    "time": Box(-inf, inf, (), float32),
    "timers": Box(-2147483648, 2147483647, (53,), int32),
    "velocity": Box(-inf, inf, (3,), float32),
    "version": Box(-inf, inf, (), float32),
    "version_field": Box(-2147483648, 2147483647, (), int32),
    "yaw_pitch_roll": Box(-inf, inf, (3,), float32),
    }

from gymnasium import spaces
import numpy as np

def get_flattened_dict_dim(space_list : list[spaces.Space]) -> int:
    total_dim = 0

    for space in space_list:
        if isinstance(space, spaces.Box):
            total_dim += int(np.prod(space.shape))

        elif isinstance(space, spaces.Discrete):
            total_dim += 1  # or `space.n` for one-hot

        elif isinstance(space, spaces.MultiBinary):
            total_dim += space.n

        elif isinstance(space, spaces.MultiDiscrete):
            total_dim += len(space.nvec)

        else:
            raise NotImplementedError(f"Unsupported space type ': {type(space)}'")

    return total_dim