defaults:
  - platforms: labpc.yaml  # or platforms/windows
  - rl_env: single_agent_env.yaml
  - sb3: ppo.yaml
  - wandb_callbacks : sb3_callback.yaml
  - models: linesight_cnn.yaml

learn_args:
  total_timesteps: 4000000
  log_interval: 13
  reset_num_timesteps: True
  progress_bar: True
  tb_log_name: "PPO"

gmi:
  launch: True
  tm_loader_profile_name: "default"
  headless: False
  port: 8775
  track : Level1.Challenge.Gbx    ##be sure to also choose correcte reference line; TODO : move to similar location or remove name dependency.
  automatic_prevent_sim_finish : True

image:
  width: 100
  height: 100

wandb:
  use: True
  entity : tmnf-practical-ss25
  project : tmnf_ppo

