defaults:
  - platforms: windows.yaml  # or platforms/windows
  - models: pretrained_resnet.yaml
  - rl_env: single_agent_env.yaml
  - sb3: ppo.yaml
  - wandb_callbacks : sb3_callback.yaml
  - models: linesight_cnn.yaml

gmi:
  launch: True
  tm_loader_profile_name: "default"
  headless: False
  port: 8775
  track : simple1_validated.Challenge.Gbx

image:
  width: 100
  height: 100

wandb:
  use: True
  entity : tmnf-practical-ss25
  project : tmnf_ppo

