name: "sophy"
progress_weight: 0.014          # cd
off_course_penalty_weight: 0.034 # co (λo = 10)
wall_penalty_weight: 0 #10.0        # λw
steering_change_penalty_weight: 3.0  # λs
steering_history_penalty_weight: 5.0 
c_d : 0.014
c_s : 182.883569
c_o :  0.034
maxlen_history: 3