site_name: trackmania-gym Documentation
nav:
  - Home : index.md 
  - Installation : installation.md
  - Structure : project-structure.md
  - Testing : testing.md
  - About : about.md
theme: readthedocs