site_name: trackmania-gym Documentation
site_url : https://dersiwi.github.io/trackmania-gym/
nav:
  - Home : index.md 
  - Installation : installation.md
  - Measure Of Progress : refline.md
  - Process-Structure : project-structure.md
  - Environment : environment.md
  - Managers : managers.md
  - Build your Agent : build-your-agent.md
  - Live-Testing : testing.md
  - Headless : headless.md
  - Future Work : future_work.md
  - About : about.md
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:  
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
theme: readthedocs