constructor:
  _partial_: true
  _target_: stable_baselines3.PPO
  policy: "MultiInputPolicy"
  verbose: 1
  n_steps : 10

learn_args:
  total_timesteps: 50
  log_interval: 1
  tb_log_name: "PPO"
  reset_num_timesteps: True
  progress_bar: False
        